AWSTemplateFormatVersion: "2010-09-09"
Description: Static Website
Resources:

  S3BucketRoot:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub '${AWS::StackName}-adcounselling-root'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketRoot
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: 's3:GetObject'
            Principal:
              CanonicalUser: !Sub '${CloudFrontOriginAccessIdentity.S3CanonicalUserId}'
            Resource: !Sub '${S3BucketRoot.Arn}/*'

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Website

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          TargetOriginId: !Sub 'S3-${AWS::StackName}-root'
          ViewerProtocolPolicy: 'redirect-to-https'
          ForwardedValues:
            QueryString: false
        DefaultRootObject: 'index.html'
        CustomErrorResponses:
          - ErrorCode: '400'
            ResponseCode: '404'
            ResponsePagePath: '/error.html'
          - ErrorCode: '403'
            ResponseCode: '404'
            ResponsePagePath: '/error.html'
          - ErrorCode: '404'
            ResponseCode: '404'
            ResponsePagePath: '/error.html'
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - DomainName: !GetAtt S3BucketRoot.DomainName
            Id: !Sub 'S3-${AWS::StackName}-root'
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Sub: 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        PriceClass: PriceClass_All
